"""Tests for the sliced 3MF parser (flashforge.threemf).

The fixtures under tests/fixtures/threemf are trimmed from real slicer output:
the real slice_info.config, the real G-code header and summary comments, a
1x1 placeholder plate image, and no toolpath. They keep the files at ~2 KB
while every value the parser reads is what the slicer actually wrote.
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

import pytest

from flashforge import threemf
from flashforge.exceptions import FlashForgeError
from flashforge.threemf import (
    PrinterFamily,
    ThreeMFError,
    ThreeMFFormatError,
    ThreeMFMultiplePlatesError,
    ThreeMFNotSlicedError,
    parse_3mf,
    printer_family_from_model_id,
    translate_warning,
)

FIXTURES = Path(__file__).parent / "fixtures" / "threemf"

SLICE_INFO_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<config>
  <plate>
    <metadata key="index" value="{index}"/>
    <metadata key="printer_model_id" value="{model}"/>
    <metadata key="prediction" value="600"/>
    <metadata key="weight" value="4.20"/>
    {filaments}
  </plate>
</config>
"""

GCODE_HEADER = """; HEADER_BLOCK_START
; generated by Orca-Flashforge 1.4.2 on 2025-11-12 at 17:40:16
; total layer number: 12
; HEADER_BLOCK_END

; filament used [mm] = 1000.00, 2500.00
; filament used [g] = 3.00, 7.50
; total filament used [g] = 10.50
; estimated printing time (normal mode) = 1h 2m 3s

; CONFIG_BLOCK_START
; filament_colour = #112233;#AABBCC
; filament_type = PLA;PETG
; printer_model = Flashforge AD5X
; CONFIG_BLOCK_END
; EXECUTABLE_BLOCK_START
G28
"""


def build_3mf(
    path: Path,
    *,
    slice_info: str | None = None,
    plates: dict[int, str] | None = None,
    thumbnail: bytes | None = b"\x89PNG-fake",
) -> Path:
    """Write a minimal 3MF archive for a test case."""
    plates = {1: GCODE_HEADER} if plates is None else plates
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", "<Types/>")
        if slice_info is not None:
            archive.writestr("Metadata/slice_info.config", slice_info)
        for index, gcode in plates.items():
            archive.writestr(f"Metadata/plate_{index}.gcode", gcode)
            if thumbnail is not None:
                archive.writestr(f"Metadata/plate_{index}.png", thumbnail)
    return path


def filament_xml(filament_id: int, material: str, color: str, grams: float) -> str:
    return (
        f'<filament id="{filament_id}" type="{material}" color="{color}" '
        f'used_m="1.00" used_g="{grams}" />'
    )


# --------------------------------------------------------------------------- #
# Real slicer output
# --------------------------------------------------------------------------- #


def test_orca_flashforge_130_single_color_5m_pro():
    result = parse_3mf(FIXTURES / "orca-flashforge-1.3.0_5mpro.3mf")

    assert result.file_name == "orca-flashforge-1.3.0_5mpro.3mf"
    assert result.plate_index == 1
    assert result.printer_model_id == "Flashforge-Adventurer-5M-Pro"
    assert result.printer_family is PrinterFamily.ADVENTURER_5M_PRO
    assert result.slicer_name == "Orca-Flashforge"
    assert result.slicer_version == "1.3.0"
    assert result.estimated_time_s == 433
    assert result.total_weight_g == pytest.approx(3.64)
    assert result.layer_count == 10
    assert result.support_used is False
    assert result.nozzle_diameters == [0.4]
    assert result.tool_count == 1
    filament = result.filaments[0]
    assert (filament.filament_id, filament.tool_id) == (1, 0)
    assert filament.material_name == "PLA"
    assert filament.color == "#C0C0C0"
    assert filament.used_g == pytest.approx(3.64)
    assert filament.used_m == pytest.approx(1.22)
    assert result.warnings == []
    assert result.thumbnail_png is not None
    assert result.thumbnail_png.startswith(b"\x89PNG")


def test_flash_studio_creator_5_pro_two_colors():
    result = parse_3mf(FIXTURES / "flashstudio-1.7.6_c5pro-2color.3mf")

    assert result.printer_model_id == "Flashforge-Creator-5-Pro"
    assert result.printer_family is PrinterFamily.CREATOR_5_PRO
    # A slicer name with a space in it must stay whole.
    assert result.slicer_name == "Flash Studio"
    assert result.slicer_version == "1.7.6"
    assert result.estimated_time_s == 1698
    assert result.first_layer_time_s == pytest.approx(147.933517)
    assert result.nozzle_diameters == [0.4, 0.4, 0.4, 0.4]
    assert [(f.tool_id, f.material_name, f.color) for f in result.filaments] == [
        (0, "PLA", "#FFFFFF"),
        (1, "PLA", "#00C1AE"),
    ]
    assert len(result.warnings) == 1
    warning = result.warnings[0]
    assert warning.key == "bed_temperature_too_high_than_filament"
    assert warning.message.startswith("The current hot bed temperature is relatively high.")
    assert warning.level == 3
    assert warning.error_code == "1000C001"


def test_orcaslicer_232_ad5x_two_colors():
    result = parse_3mf(FIXTURES / "orcaslicer-2.3.2_ad5x-2color.3mf")

    assert result.printer_family is PrinterFamily.AD5X
    assert result.slicer_name == "OrcaSlicer"
    assert result.slicer_version == "2.3.2"
    assert [(f.tool_id, f.color, f.used_g) for f in result.filaments] == [
        (0, "#FFFFFF", 3.57),
        (1, "#FF0000", 1.69),
    ]


def test_orca_flashforge_142_mixed_materials():
    result = parse_3mf(FIXTURES / "orca-flashforge-1.4.2_ad5x-pla-silk.3mf")

    assert [(f.tool_id, f.material_name) for f in result.filaments] == [
        (0, "PLA"),
        (1, "SILK"),
    ]


def test_accepts_a_binary_file_object():
    data = (FIXTURES / "orcaslicer-2.3.2_ad5x-2color.3mf").read_bytes()

    result = parse_3mf(io.BytesIO(data), file_name="upload.3mf")

    assert result.file_name == "upload.3mf"
    assert result.tool_count == 2


def test_file_object_without_a_name_gets_a_placeholder():
    data = (FIXTURES / "orcaslicer-2.3.2_ad5x-2color.3mf").read_bytes()

    assert parse_3mf(io.BytesIO(data)).file_name == "unknown.3mf"


# --------------------------------------------------------------------------- #
# Filament ids and tool ids
# --------------------------------------------------------------------------- #


def test_only_used_filaments_are_listed_and_keep_their_ids(tmp_path):
    """A file that uses filament 3 alone maps tool 2, not tool 0."""
    slice_info = SLICE_INFO_TEMPLATE.format(
        index=1, model="Flashforge-AD5X", filaments=filament_xml(3, "PETG", "#00FF00", 2.5)
    )
    result = parse_3mf(build_3mf(tmp_path / "t.3mf", slice_info=slice_info))

    assert [(f.filament_id, f.tool_id) for f in result.filaments] == [(3, 2)]


def test_filaments_are_sorted_by_id(tmp_path):
    filaments = filament_xml(2, "PLA", "#000000", 1) + filament_xml(1, "PLA", "#FFFFFF", 1)
    slice_info = SLICE_INFO_TEMPLATE.format(index=1, model="x", filaments=filaments)

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", slice_info=slice_info))

    assert [f.filament_id for f in result.filaments] == [1, 2]


def test_filament_without_a_valid_id_is_skipped(tmp_path):
    filaments = '<filament type="PLA" color="#FFFFFF" />' + filament_xml(1, "PLA", "#FFFFFF", 1)
    slice_info = SLICE_INFO_TEMPLATE.format(index=1, model="x", filaments=filaments)

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", slice_info=slice_info))

    assert [f.filament_id for f in result.filaments] == [1]


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        ("#0080ff", "#0080FF"),
        ("#0080FFCC", "#0080FF"),
        ("#0af", "#00AAFF"),
        ("0080FF", "#0080FF"),
        ("", ""),
        ("red", ""),
        ("#12345", ""),
    ],
)
def test_colors_are_normalized(tmp_path, raw, expected):
    slice_info = SLICE_INFO_TEMPLATE.format(
        index=1, model="x", filaments=filament_xml(1, "PLA", raw, 1)
    )

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", slice_info=slice_info))

    assert result.filaments[0].color == expected


# --------------------------------------------------------------------------- #
# G-code header fallback
# --------------------------------------------------------------------------- #


def test_header_fills_in_when_slice_info_is_missing(tmp_path):
    result = parse_3mf(build_3mf(tmp_path / "t.3mf", slice_info=None))

    assert result.printer_model_id == "Flashforge AD5X"
    assert result.printer_family is PrinterFamily.AD5X
    assert result.estimated_time_s == 3723
    assert result.total_weight_g == pytest.approx(10.5)
    assert result.layer_count == 12
    assert [
        (f.tool_id, f.material_name, f.color, f.used_g, f.used_m) for f in result.filaments
    ] == [
        (0, "PLA", "#112233", 3.0, 1.0),
        (1, "PETG", "#AABBCC", 7.5, 2.5),
    ]


def test_header_filament_id_list_wins_over_weights(tmp_path):
    gcode = GCODE_HEADER.replace("; HEADER_BLOCK_END", "; filament: 2\n; HEADER_BLOCK_END")

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", plates={1: gcode}))

    assert [(f.filament_id, f.material_name) for f in result.filaments] == [(2, "PETG")]


def test_header_skips_filaments_with_zero_weight(tmp_path):
    gcode = GCODE_HEADER.replace("3.00, 7.50", "0.00, 7.50")

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", plates={1: gcode}))

    assert [f.filament_id for f in result.filaments] == [2]


def test_slice_info_values_win_over_the_header(tmp_path):
    slice_info = SLICE_INFO_TEMPLATE.format(
        index=1, model="Flashforge-Creator-5", filaments=filament_xml(1, "PLA", "#FFFFFF", 1)
    )

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", slice_info=slice_info))

    assert result.printer_model_id == "Flashforge-Creator-5"
    assert result.estimated_time_s == 600
    assert result.total_weight_g == pytest.approx(4.2)
    assert result.tool_count == 1


def test_legacy_orca_eta_format(tmp_path):
    gcode = (
        "; HEADER_BLOCK_START\n"
        "; generated by Orca-Flashforge 1.2.0 on 2024-12-03 at 15:16:09\n"
        "; HEADER_BLOCK_END\n"
        "; model printing time: 43m 42s; total estimated time: 1h 43m 42s\n"
    )

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", plates={1: gcode}))

    assert result.estimated_time_s == 6222


def test_eta_with_days(tmp_path):
    gcode = GCODE_HEADER.replace("1h 2m 3s", "1d 2h 0m 5s")

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", plates={1: gcode}))

    assert result.estimated_time_s == 93605


def test_header_scan_stops_at_the_executable_block(tmp_path):
    gcode = "; EXECUTABLE_BLOCK_START\n; total layer number: 99\n"

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", plates={1: gcode}))

    assert result.layer_count is None
    assert result.filaments == []


def test_header_scan_is_bounded(tmp_path, monkeypatch):
    monkeypatch.setattr(threemf.parser, "MAX_GCODE_HEADER_BYTES", 64)
    gcode = ";" + " " * 100 + "\n; total layer number: 7\n"

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", plates={1: gcode}))

    assert result.layer_count is None


def test_file_without_any_filament_data_has_no_tools(tmp_path):
    result = parse_3mf(build_3mf(tmp_path / "t.3mf", plates={1: "G28\n"}))

    assert result.tool_count == 0
    assert result.slicer_name is None
    assert result.estimated_time_s is None


# --------------------------------------------------------------------------- #
# Plates
# --------------------------------------------------------------------------- #


def test_project_file_without_gcode_is_not_sliced(tmp_path):
    path = build_3mf(tmp_path / "project.3mf", plates={})

    with pytest.raises(ThreeMFNotSlicedError, match="holds no sliced G-code"):
        parse_3mf(path)


def test_multiple_plates_are_rejected(tmp_path):
    path = build_3mf(tmp_path / "t.3mf", plates={1: GCODE_HEADER, 2: GCODE_HEADER})

    with pytest.raises(ThreeMFMultiplePlatesError) as excinfo:
        parse_3mf(path)

    assert excinfo.value.plate_count == 2
    assert "single plate" in str(excinfo.value)


def test_single_plate_other_than_one_uses_its_own_metadata(tmp_path):
    slice_info = (
        '<config><plate><metadata key="index" value="1"/>'
        '<metadata key="printer_model_id" value="wrong"/></plate>'
        '<plate><metadata key="index" value="3"/>'
        '<metadata key="printer_model_id" value="Flashforge-AD5X"/>'
        + filament_xml(2, "PLA", "#FFFFFF", 1)
        + "</plate></config>"
    )
    path = build_3mf(tmp_path / "t.3mf", slice_info=slice_info, plates={3: GCODE_HEADER})

    result = parse_3mf(path)

    assert result.plate_index == 3
    assert result.printer_model_id == "Flashforge-AD5X"
    assert [f.tool_id for f in result.filaments] == [1]


def test_missing_thumbnail_is_none(tmp_path):
    result = parse_3mf(build_3mf(tmp_path / "t.3mf", thumbnail=None))

    assert result.thumbnail_png is None


def test_oversized_thumbnail_is_dropped(tmp_path, monkeypatch):
    monkeypatch.setattr(threemf.parser, "MAX_THUMBNAIL_BYTES", 4)

    result = parse_3mf(build_3mf(tmp_path / "t.3mf", thumbnail=b"0123456789"))

    assert result.thumbnail_png is None


# --------------------------------------------------------------------------- #
# Malformed input
# --------------------------------------------------------------------------- #


def test_not_a_zip(tmp_path):
    path = tmp_path / "t.3mf"
    path.write_bytes(b"this is not a zip archive")

    with pytest.raises(ThreeMFFormatError, match="not a readable 3MF archive"):
        parse_3mf(path)


def test_missing_file_raises_file_not_found(tmp_path):
    with pytest.raises(FileNotFoundError):
        parse_3mf(tmp_path / "missing.3mf")


def test_malformed_slice_info(tmp_path):
    path = build_3mf(tmp_path / "t.3mf", slice_info="<config><plate>")

    with pytest.raises(ThreeMFFormatError, match="malformed slice_info.config"):
        parse_3mf(path)


def test_oversized_slice_info(tmp_path, monkeypatch):
    monkeypatch.setattr(threemf.parser, "MAX_SLICE_INFO_BYTES", 16)
    slice_info = SLICE_INFO_TEMPLATE.format(index=1, model="x", filaments="")

    with pytest.raises(ThreeMFFormatError, match="oversized"):
        parse_3mf(build_3mf(tmp_path / "t.3mf", slice_info=slice_info))


def test_corrupt_entry(tmp_path):
    path = build_3mf(
        tmp_path / "t.3mf",
        slice_info=SLICE_INFO_TEMPLATE.format(
            index=1, model="x", filaments=filament_xml(1, "PLA", "#FFFFFF", 1)
        ),
    )
    data = bytearray(path.read_bytes())
    # Flip bytes inside the slice_info entry's compressed data.
    offset = data.index(b"Metadata/slice_info.config") + len("Metadata/slice_info.config") + 5
    for i in range(offset, offset + 20):
        data[i] ^= 0xFF
    path.write_bytes(bytes(data))

    with pytest.raises(ThreeMFFormatError):
        parse_3mf(path)


def test_slice_info_without_plates_falls_back_to_header(tmp_path):
    path = build_3mf(tmp_path / "t.3mf", slice_info="<config></config>")

    result = parse_3mf(path)

    assert result.tool_count == 2


def test_errors_share_the_library_base_class():
    assert issubclass(ThreeMFError, FlashForgeError)
    for error in (ThreeMFFormatError, ThreeMFNotSlicedError, ThreeMFMultiplePlatesError):
        assert issubclass(error, ThreeMFError)


# --------------------------------------------------------------------------- #
# Printer families and warnings
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    ("model_id", "expected"),
    [
        ("Flashforge-Adventurer-5M", PrinterFamily.ADVENTURER_5M),
        ("Flashforge-Adventurer-5M-Pro", PrinterFamily.ADVENTURER_5M_PRO),
        ("Flashforge Adventurer 5M Pro", PrinterFamily.ADVENTURER_5M_PRO),
        ("Flashforge-AD5X", PrinterFamily.AD5X),
        ("Flashforge AD5X", PrinterFamily.AD5X),
        ("Flashforge-Creator-5", PrinterFamily.CREATOR_5),
        ("Flashforge-Creator-5-Pro", PrinterFamily.CREATOR_5_PRO),
        ("Flashforge Creator 5 Pro", PrinterFamily.CREATOR_5_PRO),
        ("Bambu Lab X1 Carbon", None),
        ("", None),
        (None, None),
    ],
)
def test_printer_family_from_model_id(model_id, expected):
    assert printer_family_from_model_id(model_id) is expected


def test_translate_known_warning():
    assert translate_warning("not_generate_timelapse") == (
        "Timelapse will not be generated for this print."
    )


def test_translate_unknown_warning_is_prettified():
    assert translate_warning("some_new_slicer_warning") == "Some new slicer warning"


def test_translate_empty_warning():
    assert translate_warning("") == ""


def test_parsed_model_is_immutable():
    result = parse_3mf(FIXTURES / "orca-flashforge-1.3.0_5mpro.3mf")

    with pytest.raises(Exception):  # noqa: B017 - pydantic raises ValidationError
        result.file_name = "other.3mf"  # type: ignore[misc]


def test_thumbnail_is_left_out_of_repr():
    result = parse_3mf(FIXTURES / "orca-flashforge-1.3.0_5mpro.3mf")

    assert "thumbnail_png" not in repr(result)
