"""
FlashForge Python API - Sliced 3MF parser

Reads what a client needs to know about a sliced ``.3mf`` before it sends the
file to a printer: which filaments (tools) the print uses, with their material
and color, plus the plate thumbnail, time and weight estimates, the printer model
the file was sliced for, and any slicer warnings.

This is the information a client needs to build material mappings. The Creator 5
series does not report a stored file's tools, so for that family, parsing the
3MF before upload is the only way to map tools to Material Station slots
correctly.

Tested with output from Orca-FlashForge, OrcaSlicer, Flash Studio and Snapmaker
Orca. The fields
match ``ThreeMfParser`` in the TypeScript ``slicer-meta`` package.

The parser reads only small, bounded parts of the archive: the slice metadata,
the plate image and the start of the plate G-code. It never decompresses the
whole G-code, so a large or hostile archive costs a bounded amount of memory.
Parsing is synchronous file I/O. In an asyncio program, run it in an executor
(for example ``await asyncio.to_thread(parse_3mf, path)``).
"""

from __future__ import annotations

import os
import re
import zipfile
import zlib
from enum import StrEnum
from typing import IO, TypeVar
from xml.etree import ElementTree

from pydantic import BaseModel, ConfigDict, Field

from ..exceptions import FlashForgeError
from .warnings import translate_warning

# Size limits for the parts of the archive the parser reads. A real
# slice_info.config is 1-2 KB and a plate image well under 100 KB, so these
# bounds only ever stop a malformed or hostile archive.
MAX_SLICE_INFO_BYTES = 4 * 1024 * 1024
MAX_THUMBNAIL_BYTES = 8 * 1024 * 1024
# How much of the plate G-code to scan for the header comments. The header and
# the summary block sit at the start of the file; embedded thumbnails can push
# the summary back by a few hundred KB, so the scan stops at the first
# executable line or at this bound, whichever comes first.
MAX_GCODE_HEADER_BYTES = 1024 * 1024

_T = TypeVar("_T")

_SLICE_INFO = "Metadata/slice_info.config"
_PLATE_GCODE = re.compile(r"^Metadata/plate_(\d+)\.gcode$")
_HEX6 = re.compile(r"^#[0-9A-Fa-f]{6}$")
_HEX8 = re.compile(r"^#[0-9A-Fa-f]{8}$")
_HEX3 = re.compile(r"^#[0-9A-Fa-f]{3}$")
_GENERATED_BY = re.compile(r"^;\s*generated by\s+(.+?)\s+(\d\S*)(?:\s+on\s|\s*$)", re.IGNORECASE)
_DURATION = re.compile(r"(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?")


class ThreeMFError(FlashForgeError):
    """Base class for errors raised while reading a 3MF file."""


class ThreeMFFormatError(ThreeMFError):
    """The file is not a readable 3MF archive, or its slice metadata is malformed."""


class ThreeMFNotSlicedError(ThreeMFError):
    """
    The archive holds no sliced plate G-code.

    A project 3MF saved from the slicer has models but no G-code, so a printer
    cannot print it. Export the sliced plate from the slicer instead.
    """


class ThreeMFMultiplePlatesError(ThreeMFError):
    """
    The archive holds more than one sliced plate.

    Which plate a printer prints from such a file is not known, so a client
    cannot tell which tools and materials the print uses. Export a single plate
    from the slicer instead.
    """

    def __init__(self, plate_count: int) -> None:
        """
        Args:
            plate_count: The number of sliced plates in the archive.
        """
        super().__init__(
            f"This 3MF holds {plate_count} sliced plates. Export a single plate from the "
            "slicer and try again."
        )
        self.plate_count = plate_count


class PrinterFamily(StrEnum):
    """The printer model a 3MF was sliced for, as far as this library can tell."""

    ADVENTURER_5M = "adventurer_5m"
    ADVENTURER_5M_PRO = "adventurer_5m_pro"
    AD5X = "ad5x"
    CREATOR_5 = "creator_5"
    CREATOR_5_PRO = "creator_5_pro"


def printer_family_from_model_id(model_id: str | None) -> PrinterFamily | None:
    """
    Map a slicer printer-model id to a printer family.

    Slicers write ids such as ``Flashforge-Adventurer-5M-Pro``, ``Flashforge-AD5X``
    and ``Flashforge-Creator-5-Pro``. The comparison ignores case, spaces, hyphens
    and underscores, so ``Flashforge Adventurer 5M Pro`` matches too.

    Args:
        model_id: The id from the file, or ``None``.

    Returns:
        The matching family, or ``None`` for an unknown or missing id.
    """
    if not model_id:
        return None
    folded = re.sub(r"[\s_\-]+", "", model_id).lower()
    if "ad5x" in folded:
        return PrinterFamily.AD5X
    if "creator5pro" in folded:
        return PrinterFamily.CREATOR_5_PRO
    if "creator5" in folded:
        return PrinterFamily.CREATOR_5
    if "5mpro" in folded:
        return PrinterFamily.ADVENTURER_5M_PRO
    if "adventurer5m" in folded or folded.endswith("ad5m"):
        return PrinterFamily.ADVENTURER_5M
    return None


class ThreeMFFilament(BaseModel):
    """One filament (tool) that the sliced plate uses."""

    model_config = ConfigDict(frozen=True)

    filament_id: int = Field(description="The slicer's filament number (1-based)")
    tool_id: int = Field(
        description=(
            "The tool id a material mapping uses for this filament (0-based: filament 1 "
            "is tool 0)"
        )
    )
    material_name: str = Field(default="", description="Material type, e.g. 'PLA'")
    color: str = Field(
        default="", description="Filament color as #RRGGBB, or '' if the file has none"
    )
    used_m: float | None = Field(default=None, description="Filament length used, in meters")
    used_g: float | None = Field(default=None, description="Filament weight used, in grams")


class ThreeMFWarning(BaseModel):
    """A warning the slicer recorded for the plate."""

    model_config = ConfigDict(frozen=True)

    key: str = Field(description="Raw warning key, e.g. 'bed_temperature_too_high_than_filament'")
    message: str = Field(description="Readable text for the key")
    level: int = Field(default=0, description="Severity level as the slicer wrote it")
    error_code: str = Field(default="", description="The slicer's error code, if any")


class ThreeMFFile(BaseModel):
    """What a sliced 3MF says about its print."""

    model_config = ConfigDict(frozen=True)

    file_name: str = Field(description="The file's base name")
    plate_index: int = Field(description="The index of the sliced plate (1-based)")
    printer_model_id: str | None = Field(
        default=None, description="The printer model id the file was sliced for"
    )
    slicer_name: str | None = Field(default=None, description="e.g. 'Orca-Flashforge'")
    slicer_version: str | None = Field(default=None, description="e.g. '1.4.2'")
    estimated_time_s: int | None = Field(
        default=None, description="The slicer's print time estimate, in seconds"
    )
    total_weight_g: float | None = Field(
        default=None, description="Total filament weight, in grams"
    )
    first_layer_time_s: float | None = Field(
        default=None, description="The slicer's first-layer time estimate, in seconds"
    )
    layer_count: int | None = Field(default=None, description="Total layer count")
    support_used: bool = Field(default=False, description="Whether the plate uses supports")
    nozzle_diameters: list[float] = Field(
        default_factory=list, description="Nozzle diameter per extruder, in mm"
    )
    object_names: list[str] = Field(
        default_factory=list, description="Names of the objects on the plate"
    )
    filaments: list[ThreeMFFilament] = Field(
        default_factory=list, description="The filaments the plate uses, by filament id"
    )
    warnings: list[ThreeMFWarning] = Field(
        default_factory=list, description="Warnings the slicer recorded"
    )
    thumbnail_png: bytes | None = Field(
        default=None, repr=False, description="The plate preview image (PNG bytes)"
    )

    @property
    def tool_count(self) -> int:
        """The number of filaments (tools) the plate uses."""
        return len(self.filaments)

    @property
    def printer_family(self) -> PrinterFamily | None:
        """The printer family the file was sliced for, if the id is known."""
        return printer_family_from_model_id(self.printer_model_id)


def parse_3mf(
    source: str | os.PathLike[str] | IO[bytes],
    *,
    file_name: str | None = None,
) -> ThreeMFFile:
    """
    Parse a sliced 3MF file.

    Args:
        source: A path to the file, or a binary file object open for reading.
        file_name: The name to report in :attr:`ThreeMFFile.file_name`. Defaults
            to the base name of ``source`` when it is a path.

    Returns:
        The parsed metadata.

    Raises:
        FileNotFoundError: If ``source`` is a path that does not exist.
        ThreeMFFormatError: If the file is not a valid ZIP archive, has a corrupt
            entry, or its slice metadata is malformed or too large.
        ThreeMFNotSlicedError: If the archive holds no sliced plate G-code.
        ThreeMFMultiplePlatesError: If the archive holds more than one sliced plate.
    """
    if file_name is None:
        file_name = (
            os.path.basename(os.fspath(source))
            if isinstance(source, (str, os.PathLike))
            else "unknown.3mf"
        )

    try:
        archive = zipfile.ZipFile(source)
    except FileNotFoundError:
        raise
    except (zipfile.BadZipFile, OSError, ValueError) as err:
        raise ThreeMFFormatError(f"'{file_name}' is not a readable 3MF archive: {err}") from err

    with archive:
        try:
            return _parse_archive(archive, file_name)
        except (zipfile.BadZipFile, zlib.error, EOFError, NotImplementedError) as err:
            # A corrupt entry (bad CRC, truncated or unsupported compression).
            raise ThreeMFFormatError(f"'{file_name}' has a corrupt entry: {err}") from err


def _parse_archive(archive: zipfile.ZipFile, file_name: str) -> ThreeMFFile:
    plates: dict[int, str] = {}
    for name in archive.namelist():
        match = _PLATE_GCODE.match(name)
        if match:
            plates[int(match.group(1))] = name

    if not plates:
        raise ThreeMFNotSlicedError(
            f"'{file_name}' holds no sliced G-code. Slice the plate and export the sliced "
            "file from the slicer."
        )
    if len(plates) > 1:
        raise ThreeMFMultiplePlatesError(len(plates))

    plate_index, gcode_name = next(iter(plates.items()))

    fields: dict[str, object] = {"file_name": file_name, "plate_index": plate_index}
    filaments: list[ThreeMFFilament] = []

    if _SLICE_INFO in archive.namelist():
        raw = _read_bounded(archive, _SLICE_INFO, MAX_SLICE_INFO_BYTES)
        if raw is None:
            raise ThreeMFFormatError(f"'{file_name}' has an oversized slice_info.config.")
        filaments = _parse_slice_info(raw, plate_index, fields, file_name)

    header = _scan_gcode_header(archive, gcode_name)
    _apply_gcode_header(header, fields)
    if not filaments:
        filaments = _filaments_from_header(header)
    fields["filaments"] = filaments

    thumbnail_name = f"Metadata/plate_{plate_index}.png"
    if thumbnail_name in archive.namelist():
        fields["thumbnail_png"] = _read_bounded(archive, thumbnail_name, MAX_THUMBNAIL_BYTES)

    return ThreeMFFile.model_validate(fields)


def _read_bounded(archive: zipfile.ZipFile, name: str, limit: int) -> bytes | None:
    """Read one entry, or return None when it is larger than ``limit``."""
    if archive.getinfo(name).file_size > limit:
        return None
    with archive.open(name) as handle:
        data = handle.read(limit + 1)
    # file_size comes from the archive and can lie, so check what was read too.
    return None if len(data) > limit else data


# --------------------------------------------------------------------------- #
# slice_info.config
# --------------------------------------------------------------------------- #


def _parse_slice_info(
    raw: bytes, plate_index: int, fields: dict[str, object], file_name: str
) -> list[ThreeMFFilament]:
    try:
        root = ElementTree.fromstring(raw)
    except ElementTree.ParseError as err:
        raise ThreeMFFormatError(f"'{file_name}' has a malformed slice_info.config: {err}") from err

    plates = root.findall("plate")
    if not plates:
        return []

    plate = plates[0]
    for candidate in plates:
        if _plate_metadata(candidate).get("index") == str(plate_index):
            plate = candidate
            break

    meta = _plate_metadata(plate)
    if meta.get("printer_model_id"):
        fields["printer_model_id"] = meta["printer_model_id"]
    prediction = _to_float(meta.get("prediction"))
    if prediction is not None:
        fields["estimated_time_s"] = int(round(prediction))
    weight = _to_float(meta.get("weight"))
    if weight is not None:
        fields["total_weight_g"] = weight
    first_layer = _to_float(meta.get("first_layer_time"))
    if first_layer is not None:
        fields["first_layer_time_s"] = first_layer
    fields["support_used"] = meta.get("support_used", "").lower() in ("true", "1")
    fields["nozzle_diameters"] = [
        value
        for value in (
            _to_float(part) for part in re.split(r"[,\s]+", meta.get("nozzle_diameters", ""))
        )
        if value is not None
    ]
    fields["object_names"] = [
        obj.get("name", "") for obj in plate.findall("object") if obj.get("name")
    ]
    fields["warnings"] = [
        ThreeMFWarning(
            key=warning.get("msg", ""),
            message=translate_warning(warning.get("msg", "")),
            level=_to_int(warning.get("level")) or 0,
            error_code=warning.get("error_code", "") or "",
        )
        for warning in plate.findall("warning")
    ]

    filaments: list[ThreeMFFilament] = []
    for element in plate.findall("filament"):
        filament_id = _to_int(element.get("id"))
        if filament_id is None or filament_id < 1:
            continue
        filaments.append(
            ThreeMFFilament(
                filament_id=filament_id,
                tool_id=filament_id - 1,
                material_name=(element.get("type") or "").strip(),
                color=_normalize_color(element.get("color")),
                used_m=_to_float(element.get("used_m")),
                used_g=_to_float(element.get("used_g")),
            )
        )
    filaments.sort(key=lambda item: item.filament_id)
    return filaments


def _plate_metadata(plate: ElementTree.Element) -> dict[str, str]:
    return {
        item.get("key", ""): item.get("value", "") or ""
        for item in plate.findall("metadata")
        if item.get("key")
    }


# --------------------------------------------------------------------------- #
# Plate G-code header
# --------------------------------------------------------------------------- #


def _scan_gcode_header(archive: zipfile.ZipFile, name: str) -> dict[str, str]:
    """
    Collect ``; key = value`` and ``; key: value`` comments from the G-code start.

    Stops at the first executable line block, at the end of the config block,
    or after :data:`MAX_GCODE_HEADER_BYTES`. The first occurrence of a key wins.
    """
    header: dict[str, str] = {}
    consumed = 0
    with archive.open(name) as handle:
        for raw_line in handle:
            consumed += len(raw_line)
            if consumed > MAX_GCODE_HEADER_BYTES:
                break
            line = raw_line.decode("utf-8", errors="replace").strip()
            if not line.startswith(";"):
                continue
            if "EXECUTABLE_BLOCK_START" in line or "CONFIG_BLOCK_END" in line:
                break
            generated = _GENERATED_BY.match(line)
            if generated and "generated_by" not in header:
                header["generated_by_name"] = generated.group(1).strip()
                header["generated_by_version"] = generated.group(2).strip()
                header["generated_by"] = line
                continue
            body = line.lstrip(";").strip()
            for separator in (" = ", ": "):
                if separator in body:
                    key, value = body.split(separator, 1)
                    header.setdefault(key.strip().lower(), value.strip())
                    break
    return header


def _apply_gcode_header(header: dict[str, str], fields: dict[str, object]) -> None:
    if header.get("generated_by_name"):
        fields["slicer_name"] = header["generated_by_name"]
        fields["slicer_version"] = header["generated_by_version"]

    if "estimated_time_s" not in fields:
        eta = next(
            (
                value
                for key, value in header.items()
                if key.startswith("estimated printing time") and "first layer" not in key
            ),
            None,
        )
        if eta is None:
            # Orca-FlashForge before 1.3.0:
            # "; model printing time: 43m 42s; total estimated time: 43m 42s"
            legacy = header.get("model printing time", "")
            if "total estimated time:" in legacy:
                eta = legacy.split("total estimated time:", 1)[1]
        seconds = _parse_duration(eta)
        if seconds is not None:
            fields["estimated_time_s"] = seconds

    layers = _to_int(header.get("total layer number")) or _to_int(header.get("total layers count"))
    if layers is not None:
        fields["layer_count"] = layers

    if "total_weight_g" not in fields:
        weight = _to_float(header.get("total filament used [g]"))
        if weight is not None:
            fields["total_weight_g"] = weight

    if "printer_model_id" not in fields and header.get("printer_model"):
        fields["printer_model_id"] = header["printer_model"]


def _filaments_from_header(header: dict[str, str]) -> list[ThreeMFFilament]:
    """
    Fall back to the G-code header when slice_info.config lists no filaments.

    Uses the ``; filament: 1,2`` id list when present, otherwise every filament
    with a non-zero weight in ``; filament used [g]``.
    """
    grams = [_to_float(part) for part in _split_list(header.get("filament used [g]"))]
    meters_mm = [_to_float(part) for part in _split_list(header.get("filament used [mm]"))]
    types = _split_list(header.get("filament_type"), separator=";")
    colors = _split_list(header.get("filament_colour"), separator=";")

    ids = [
        value for value in (_to_int(part) for part in _split_list(header.get("filament"))) if value
    ]
    if not ids:
        ids = [index + 1 for index, value in enumerate(grams) if value]
    if not ids and len(types) == 1:
        ids = [1]

    filaments: list[ThreeMFFilament] = []
    for filament_id in sorted(set(ids)):
        index = filament_id - 1
        length_mm = _pick(meters_mm, index)
        filaments.append(
            ThreeMFFilament(
                filament_id=filament_id,
                tool_id=index,
                material_name=(_pick(types, index) or "").strip(),
                color=_normalize_color(_pick(colors, index)),
                used_m=round(length_mm / 1000, 2) if length_mm is not None else None,
                used_g=_pick(grams, index),
            )
        )
    return filaments


# --------------------------------------------------------------------------- #
# Value helpers
# --------------------------------------------------------------------------- #


def _pick(values: list[_T], index: int) -> _T | None:
    return values[index] if 0 <= index < len(values) else None


def _split_list(value: str | None, separator: str = ",") -> list[str]:
    if not value:
        return []
    return [part.strip().strip('"') for part in value.split(separator)]


def _to_float(value: str | None) -> float | None:
    if value is None:
        return None
    try:
        return float(str(value).strip())
    except ValueError:
        return None


def _to_int(value: str | None) -> int | None:
    number = _to_float(value)
    return int(number) if number is not None else None


def _normalize_color(value: str | None) -> str:
    """Return ``#RRGGBB`` (upper case) for a usable color, or ``''``."""
    color = (value or "").strip()
    if color and not color.startswith("#"):
        color = f"#{color}"
    if _HEX8.match(color):
        color = color[:7]
    elif _HEX3.match(color):
        color = "#" + "".join(ch * 2 for ch in color[1:])
    return color.upper() if _HEX6.match(color) else ""


def _parse_duration(value: str | None) -> int | None:
    """Convert ``1d 2h 5m 30s`` style text to seconds."""
    if not value:
        return None
    match = next((m for m in _DURATION.finditer(value) if any(m.groups())), None)
    if match is None:
        return None
    days, hours, minutes, seconds = (int(group) if group else 0 for group in match.groups())
    return ((days * 24 + hours) * 60 + minutes) * 60 + seconds
